# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - release

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
    displayName: "Install Node.js"

  - script: |
      npm install
      npm run build
    displayName: "npm install and build"

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)/.next"
      archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
      includeRootFolder: false
    displayName: "Archive build files"

  - task: AzureRmWebAppDeployment@3
    inputs:
      azureSubscription: "Proteus Azure RM"
      WebAppName: "martinlijanto"
      Package: $(System.ArtifactsDirectory)/**/$(Build.BuildId).zip
    displayName: "Deploy build files"
